import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const OPENROUTER_URL="https://openrouter.ai/api/v1/chat/completions";
const MODEL="google/gemini-2.5-flash";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const PUBLISHABLE_KEYS=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}");
const ACCEPTED_KEYS=[PUBLISHABLE_KEYS.default,Deno.env.get("SUPABASE_ANON_KEY")].filter((x):x is string=>Boolean(x));
const BROWSER_KEY=ACCEPTED_KEYS[0]||"";
const CONTEXT={academic_program:"III MBBS Part-II",academic_term:"VII Term",batch:"J3 Batch",period_start:"2026-09-07",period_end:"2027-01-24"};
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"};
const schema={type:"object",properties:{department:{type:["string","null"]},department_code:{type:["string","null"]},classes:{type:"array",items:{type:"object",properties:{class_date:{type:["string","null"]},day:{type:["string","null"]},start_time:{type:["string","null"]},end_time:{type:["string","null"]},session_type:{type:["string","null"]},subject:{type:["string","null"]},topic:{type:["string","null"]},faculty:{type:["string","null"]},venue:{type:["string","null"]},batch:{type:["string","null"]},raw_text:{type:["string","null"]},confidence:{type:["number","null"]}},required:["class_date","day","start_time","end_time","session_type","subject","topic","faculty","venue","batch","raw_text","confidence"],additionalProperties:false}}},required:["department","department_code","classes"],additionalProperties:false};
function response(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}})}
function dataUrl(mime:string,bytes:Uint8Array){let b="";for(let i=0;i<bytes.length;i+=0x8000)b+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return`data:${mime};base64,${b}`}
async function rpc(name:string,payload:unknown){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:BROWSER_KEY,Authorization:`Bearer ${BROWSER_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${name} failed (${r.status}): ${t}`);return t?JSON.parse(t):null}
async function log(requestId:string,level:string,stage:string,message:string,metadata:Record<string,unknown>={}){try{await rpc("append_schedule_agent_log",{p_request_id:requestId,p_level:level,p_stage:stage,p_message:message,p_metadata:metadata})}catch(_){} }
Deno.serve(async(req:Request)=>{
 const requestId=crypto.randomUUID();
 await log(requestId,"info","REQUEST_RECEIVED","HTTP request reached Schedule Agent",{method:req.method,origin:req.headers.get("origin"),content_type:req.headers.get("content-type"),content_length:req.headers.get("content-length")});
 if(req.method==="OPTIONS"){await log(requestId,"info","CORS_PREFLIGHT","CORS preflight received");return response({ok:true,request_id:requestId})}
 if(req.method!=="POST"){await log(requestId,"warn","METHOD_REJECTED","Request method rejected",{method:req.method});return response({error:"POST required",request_id:requestId},405)}
 const suppliedKey=req.headers.get("apikey")||"";const bearer=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");
 if(!ACCEPTED_KEYS.length||(!ACCEPTED_KEYS.includes(suppliedKey)&&!ACCEPTED_KEYS.includes(bearer))){await log(requestId,"warn","AUTH_REJECTED","Request reached backend but API key was rejected",{has_apikey:Boolean(suppliedKey),has_authorization:Boolean(bearer),key_prefix:suppliedKey.slice(0,12)});return response({error:"Unauthorized",request_id:requestId},401)}
 await log(requestId,"info","AUTH_ACCEPTED","UI request authenticated");
 const apiKey=Deno.env.get("OPENROUTER_API_KEY");if(!apiKey){await log(requestId,"error","CONFIG","OPENROUTER_API_KEY is not configured");return response({error:"OPENROUTER_API_KEY is not configured",request_id:requestId},500)}
 try{
  await log(requestId,"info","FORM_DATA_RECEIVE","Reading multipart document upload");
  const form=await req.formData();const entries=form.getAll("files");const files=entries.filter((x):x is File=>x instanceof File);
  await log(requestId,"info","FILE_VALIDATION","Multipart form parsed",{form_file_entries:entries.length,file_count:files.length});
  if(!files.length)return response({error:"No document files supplied",request_id:requestId},400);
  if(files.length>5)return response({error:"Maximum 5 files per request",request_id:requestId},413);
  await log(requestId,"info","FILES_RECEIVED","Document files received from UI",{count:files.length,names:files.map(f=>f.name),types:files.map(f=>f.type),sizes:files.map(f=>f.size)});
  const content:any[]=[{type:"text",text:`You are the CollegeSchedule V2.3 document-native extraction agent. Target context: ${JSON.stringify(CONTEXT)}. Read ORIGINAL PDF/image documents including visual tables and scanned pages. Identify the issuing department first. Extract ONLY factual timetable classes relevant to this target context and date range. Ignore unrelated programmes, terms, batches and dates. Do not reconcile, modify or replace V1. Never fabricate date, time, batch, subject, session type, topic, faculty or venue; use null when not explicit. Expand date ranges only when clearly established. Return one object per actual class/session. Preserve the smallest useful supporting wording in raw_text. Use YYYY-MM-DD dates and HH:MM times. confidence is extraction certainty from 0 to 1. Return exactly the required JSON schema.`}];
  for(const file of files){if(!file.type.startsWith("image/")&&file.type!=="application/pdf"){await log(requestId,"warn","FILE_REJECTED","Unsupported document type",{name:file.name,type:file.type,size:file.size});return response({error:`Unsupported document type: ${file.type||file.name}. Use PDF or image.`,request_id:requestId},415)}const bytes=new Uint8Array(await file.arrayBuffer());await log(requestId,"info","FILE_READ","Document bytes read",{name:file.name,type:file.type,size:bytes.byteLength});content.push({type:"text",text:`SOURCE FILE: ${file.name}`});content.push(file.type==="application/pdf"?{type:"file",file:{filename:file.name,file_data:dataUrl(file.type,bytes)}}:{type:"image_url",image_url:{url:dataUrl(file.type,bytes)}})}
  await log(requestId,"info","ENCODING_COMPLETE","Files encoded for model request",{count:files.length});await log(requestId,"info","OPENROUTER_REQUEST","Sending original documents to OpenRouter",{model:MODEL,file_count:files.length});
  const upstream=await fetch(OPENROUTER_URL,{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json","HTTP-Referer":"https://quare-albus.github.io/CollegeSchedule/","X-Title":"CollegeSchedule Schedule Agent"},body:JSON.stringify({model:MODEL,temperature:0,messages:[{role:"user",content}],response_format:{type:"json_schema",json_schema:{name:"schedule_extraction",strict:true,schema}}})});
  const text=await upstream.text();await log(requestId,upstream.ok?"info":"error","OPENROUTER_RESPONSE","OpenRouter returned a response",{status:upstream.status,body_length:text.length});if(!upstream.ok)return response({error:"OpenRouter request failed",status:upstream.status,request_id:requestId},502);
  const payload=JSON.parse(text);const raw=payload?.choices?.[0]?.message?.content;const parsed=typeof raw==="string"?JSON.parse(raw):raw;if(!parsed||!Array.isArray(parsed.classes)||!parsed.department){await log(requestId,"error","EXTRACTION_REJECTED","Model returned invalid extraction payload");return response({error:"Extraction did not identify a department or class array",request_id:requestId},422)}
  await log(requestId,"info","EXTRACTION_COMPLETE","Model extraction completed",{department:parsed.department,class_count:parsed.classes.length});const ingest=await rpc("ingest_department_schedule",{payload:{target:CONTEXT,department:parsed.department,department_code:parsed.department_code,source_file:files.map(f=>f.name).join(", "),files_count:files.length,classes:parsed.classes}});await log(requestId,"info","PERSISTENCE_COMPLETE","Extracted classes persisted",{schedule_id:ingest.schedule_id,class_count:parsed.classes.length});const results=await rpc("get_schedule_results",{p_schedule_id:ingest.schedule_id});await log(requestId,"info","RECONCILIATION_COMPLETE","V1 reconciliation completed",{schedule_id:ingest.schedule_id,result_count:Array.isArray(results)?results.length:0});await log(requestId,"info","RESPONSE_SENT","Schedule Agent response ready",{schedule_id:ingest.schedule_id});return response({ok:true,request_id:requestId,model:MODEL,context:CONTEXT,files:files.map(f=>f.name),department:parsed.department,classes:parsed.classes,persistence:ingest,results});
 }catch(error){await log(requestId,"error","EXCEPTION","Unhandled Schedule Agent error",{error:error instanceof Error?error.message:String(error)});return response({error:error instanceof Error?error.message:String(error),request_id:requestId},500)}});