import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { PDFDocument } from "npm:pdf-lib@1.17.1";

const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";
const MODEL = "openrouter/free";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const PUBLISHABLE_KEYS = JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS") || "{}");
const ACCEPTED_KEYS = [PUBLISHABLE_KEYS.default, Deno.env.get("SUPABASE_ANON_KEY")].filter((x): x is string => Boolean(x));
const BROWSER_KEY = ACCEPTED_KEYS[0] || "";
const CONTEXT = { academic_program: "III MBBS Part-II", academic_term: "VII Term", batch: "J3 Batch", period_start: "2026-09-07", period_end: "2027-01-24" };
const CORS = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Max-Age": "86400", Vary: "Origin" };
const SCHEMA = { type: "object", properties: { department: { type: ["string", "null"] }, department_code: { type: ["string", "null"] }, classes: { type: "array", items: { type: "object", properties: { class_date: { type: ["string", "null"] }, day: { type: ["string", "null"] }, start_time: { type: ["string", "null"] }, end_time: { type: ["string", "null"] }, session_type: { type: ["string", "null"] }, subject: { type: ["string", "null"] }, topic: { type: ["string", "null"] }, faculty: { type: ["string", "null"] }, venue: { type: ["string", "null"] }, batch: { type: ["string", "null"] }, raw_text: { type: ["string", "null"] }, confidence: { type: ["number", "null"] }, source_page: { type: ["integer", "null"] } }, required: ["class_date", "day", "start_time", "end_time", "session_type", "subject", "topic", "faculty", "venue", "batch", "raw_text", "confidence", "source_page"], additionalProperties: false } } }, required: ["department", "department_code", "classes"], additionalProperties: false };
function response(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { ...CORS, "Content-Type": "application/json; charset=utf-8" } }); }
function base64(bytes: Uint8Array) { let b = ""; for (let i = 0; i < bytes.length; i += 0x8000) b += String.fromCharCode(...bytes.subarray(i, Math.min(i + 0x8000, bytes.length))); return btoa(b); }
function dataUrl(mime: string, bytes: Uint8Array) { return `data:${mime};base64,${base64(bytes)}`; }
async function rpc(name: string, payload: unknown) { const r = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, { method: "POST", headers: { apikey: BROWSER_KEY, Authorization: `Bearer ${BROWSER_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const t = await r.text(); if (!r.ok) throw new Error(`Supabase ${name} failed (${r.status}): ${t}`); return t ? JSON.parse(t) : null; }
async function log(id: string, level: string, stage: string, message: string, metadata: Record<string, unknown> = {}) { try { await rpc("append_schedule_agent_log", { p_request_id: id, p_level: level, p_stage: stage, p_message: message, p_metadata: metadata }); } catch (_) {} }
const dayMap: Record<string, string> = { sun: "Sunday", sunday: "Sunday", mon: "Monday", monday: "Monday", tue: "Tuesday", tues: "Tuesday", tuesday: "Tuesday", wed: "Wednesday", wednesday: "Wednesday", thu: "Thursday", thur: "Thursday", thurs: "Thursday", thursday: "Thursday", fri: "Friday", friday: "Friday", sat: "Saturday", saturday: "Saturday" };
function normDay(v: string | null) { return v ? dayMap[v.trim().toLowerCase()] || v.trim() : null; }
function normTime(v: string | null) { if (!v) return null; const s = v.trim().toLowerCase().replace(/\./g, ":").replace(/\s+/g, ""); const m = s.match(/^(\d{1,2})(?::(\d{1,2}))?(am|pm)?$/); if (!m) return null; let h = Number(m[1]), min = Number(m[2] || 0); if (min > 59) return null; if (m[3] === "pm" && h < 12) h += 12; if (m[3] === "am" && h === 12) h = 0; if (h > 23) return null; return `${String(h).padStart(2, "0")}:${String(min).padStart(2, "0")}`; }
function cleanRows(p: any) { return (Array.isArray(p.classes) ? p.classes : []).map((r: any) => ({ ...r, day: normDay(r.day), start_time: normTime(r.start_time), end_time: normTime(r.end_time), subject: r.subject?.trim() || null, session_type: r.session_type?.trim() || null, batch: r.batch?.trim() || null, faculty: r.faculty?.trim() || null, venue: r.venue?.trim() || null, topic: r.topic?.trim() || null, raw_text: r.raw_text?.trim() || null, confidence: r.confidence == null ? null : Math.max(0, Math.min(1, Number(r.confidence))), source_page: r.source_page == null ? null : Number(r.source_page) })).filter((r: any) => r.start_time && r.end_time && r.subject); }
function parseCsv(text: string) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(x => x.trim()); if (lines.length < 2) return []; const parse = (line: string) => { const out: string[] = []; let cur = "", q = false; for (let i = 0; i < line.length; i++) { const c = line[i]; if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; continue; } if (c === '"') { q = !q; continue; } if (c === ',' && !q) { out.push(cur.trim()); cur = ""; } else cur += c; } out.push(cur.trim()); return out; }; const h = parse(lines[0]).map(x => x.toLowerCase().replace(/[^a-z0-9]+/g, "_")); const find = (names: string[], a: string[]) => { const i = names.map(n => a.indexOf(n)).find(i => i >= 0); return i == null ? null : i; }; const idx = { date: find(["class_date", "date"], h), day: find(["day"], h), start: find(["start_time", "start"], h), end: find(["end_time", "end"], h), subject: find(["subject", "course"], h), session: find(["session_type", "type"], h), topic: find(["topic"], h), faculty: find(["faculty", "teacher"], h), venue: find(["venue", "room"], h), batch: find(["batch", "group"], h), raw: find(["raw_text", "raw"], h) }; return lines.slice(1).map(line => { const a = parse(line); return { class_date: idx.date == null ? null : a[idx.date] || null, day: idx.day == null ? null : a[idx.day] || null, start_time: idx.start == null ? null : a[idx.start] || null, end_time: idx.end == null ? null : a[idx.end] || null, subject: idx.subject == null ? null : a[idx.subject] || null, session_type: idx.session == null ? null : a[idx.session] || null, topic: idx.topic == null ? null : a[idx.topic] || null, faculty: idx.faculty == null ? null : a[idx.faculty] || null, venue: idx.venue == null ? null : a[idx.venue] || null, batch: idx.batch == null ? null : a[idx.batch] || null, raw_text: idx.raw == null ? null : a[idx.raw] || null, confidence: 1, source_page: null }; }); }
function looksLikePdf(bytes: Uint8Array) { return bytes.length >= 5 && new TextDecoder().decode(bytes.subarray(0, 5)) === "%PDF-"; }
function isSizeParserError(status: number, detail: string) { return status === 400 && /exceeds the maximum size|maximum size supported by the file parser|file parser/i.test(detail); }
async function splitPdf(bytes: Uint8Array) { const source = await PDFDocument.load(bytes); const count = source.getPageCount(); const pages: Uint8Array[] = []; for (let i = 0; i < count; i++) { const out = await PDFDocument.create(); const [page] = await out.copyPages(source, [i]); out.addPage(page); pages.push(await out.save({ useObjectStreams: true, addDefaultPage: false })); } return pages; }
function extractionPrompt(fileName: string, pageNumber: number | null, pageCount: number | null) { return `Extract a timetable into normalized rows for ${JSON.stringify(CONTEXT)}. Identify the issuing department. Read all visual table structure, including scanned pages. Extract only classes relevant to the target programme/term/batch/date range. Do not reconcile against V1. Do not infer missing values. Dates YYYY-MM-DD; times HH:MM 24-hour. Preserve raw_text and source_page. Return only the requested strict JSON schema. SOURCE FILE: ${fileName}.${pageNumber == null ? "" : ` This is page ${pageNumber} of ${pageCount}. Set source_page to ${pageNumber} for every row extracted from this page.`}`; }
async function requestPdfExtraction(openRouterKey: string, fileName: string, pdfBytes: Uint8Array, pageNumber: number | null, pageCount: number | null, engine: "cloudflare-ai" | "mistral-ocr") { const content: any[] = [{ type: "text", text: extractionPrompt(fileName, pageNumber, pageCount) }, { type: "file", file: { filename: fileName, file_data: dataUrl("application/pdf", pdfBytes) } }]; const body: any = { model: MODEL, temperature: 0, messages: [{ role: "user", content }], response_format: { type: "json_schema", json_schema: { name: "schedule_extraction", strict: true, schema: SCHEMA } }, plugins: [{ id: "file-parser", pdf: { engine } }] }; const upstream = await fetch(OPENROUTER_URL, { method: "POST", headers: { Authorization: `Bearer ${openRouterKey}`, "Content-Type": "application/json", "HTTP-Referer": "https://quare-albus.github.io/CollegeSchedule/", "X-Title": "CollegeSchedule Structured Ingest" }, body: JSON.stringify(body) }); const text = await upstream.text(); if (!upstream.ok) { let detail = text.slice(0, 1000); try { const e = JSON.parse(text); detail = String(e?.error?.message || e?.error?.code || detail); } catch {} return { ok: false, status: upstream.status, detail }; } try { const payload = JSON.parse(text); const raw = payload?.choices?.[0]?.message?.content; const parsed = typeof raw === "string" ? JSON.parse(raw) : raw; if (!parsed || !Array.isArray(parsed.classes)) return { ok: false, status: 422, detail: "Invalid structured extraction response" }; return { ok: true, parsed, provider_model: payload?.model || null }; } catch (e) { return { ok: false, status: 422, detail: `Invalid JSON response: ${e instanceof Error ? e.message : String(e)}` }; } }
async function requestImageExtraction(openRouterKey: string, fileName: string, mime: string, bytes: Uint8Array) { const content = [{ type: "text", text: extractionPrompt(fileName, null, null) }, { type: "image_url", image_url: { url: dataUrl(mime, bytes) } }]; const body: any = { model: MODEL, temperature: 0, messages: [{ role: "user", content }], response_format: { type: "json_schema", json_schema: { name: "schedule_extraction", strict: true, schema: SCHEMA } } }; const upstream = await fetch(OPENROUTER_URL, { method: "POST", headers: { Authorization: `Bearer ${openRouterKey}`, "Content-Type": "application/json", "HTTP-Referer": "https://quare-albus.github.io/CollegeSchedule/", "X-Title": "CollegeSchedule Structured Ingest" }, body: JSON.stringify(body) }); const text = await upstream.text(); if (!upstream.ok) { let detail = text.slice(0, 1000); try { const e = JSON.parse(text); detail = String(e?.error?.message || e?.error?.code || detail); } catch {} return { ok: false, status: upstream.status, detail }; } try { const payload = JSON.parse(text); const raw = payload?.choices?.[0]?.message?.content; const parsed = typeof raw === "string" ? JSON.parse(raw) : raw; if (!parsed || !Array.isArray(parsed.classes)) return { ok: false, status: 422, detail: "Invalid structured extraction response" }; return { ok: true, parsed, provider_model: payload?.model || null }; } catch (e) { return { ok: false, status: 422, detail: `Invalid JSON response: ${e instanceof Error ? e.message : String(e)}` }; } }
Deno.serve(async (req: Request) => {
  const id = crypto.randomUUID(); await log(id, "info", "INGEST_REQUEST_RECEIVED", "Structured ingest request received", { method: req.method, content_type: req.headers.get("content-type"), content_length: req.headers.get("content-length") });
  if (req.method === "OPTIONS") return response({ ok: true, request_id: id }); if (req.method !== "POST") return response({ error: "POST required", request_id: id }, 405);
  const supplied = req.headers.get("apikey") || ""; const bearer = (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, ""); if (!ACCEPTED_KEYS.length || (!ACCEPTED_KEYS.includes(supplied) && !ACCEPTED_KEYS.includes(bearer))) return response({ error: "Unauthorized", request_id: id }, 401);
  const openRouterKey = Deno.env.get("OPENROUTER_API_KEY"); if (!openRouterKey) return response({ error: "OPENROUTER_API_KEY is not configured", request_id: id }, 500);
  try {
    const form = await req.formData(); const entries = form.getAll("files"); const files = entries.filter((x): x is File => x instanceof File); if (!files.length) return response({ error: "No document files supplied", request_id: id }, 400); if (files.length > 5) return response({ error: "Maximum 5 files per request", request_id: id }, 413);
    await log(id, "info", "FILES_RECEIVED", "Files accepted for structured extraction", { count: files.length, names: files.map(f => f.name), sizes: files.map(f => f.size) });
    let all: any[] = []; let department: string | null = null; let department_code: string | null = null;
    for (const file of files) {
      const bytes = new Uint8Array(await file.arrayBuffer()); let rows: any[] = [];
      if (file.name.toLowerCase().endsWith(".csv") || file.type === "text/csv") { rows = cleanRows({ classes: parseCsv(new TextDecoder().decode(bytes)) }); await log(id, "info", "LOCAL_CSV_PARSE", "CSV parsed locally without LLM", { name: file.name, rows: rows.length }); all.push(...rows); continue; }
      const isPdf = file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf"); if (!isPdf && !file.type.startsWith("image/")) return response({ error: `Unsupported document type: ${file.type || file.name}. Use PDF, image or CSV.`, request_id: id }, 415);
      if (!isPdf) { const result = await requestImageExtraction(openRouterKey, file.name, file.type, bytes); if (!result.ok) return response({ error: "Structured extraction provider failed", status: result.status, provider_error: result.detail, request_id: id }, 502); department = department || result.parsed.department; department_code = department_code || result.parsed.department_code; all.push(...cleanRows(result.parsed)); await log(id, "info", "STRUCTURED_EXTRACTION_COMPLETE", "Image converted to normalized rows", { name: file.name, rows: result.parsed.classes.length, department, provider_model: result.provider_model }); continue; }
      if (!looksLikePdf(bytes)) return response({ error: "Invalid PDF file", request_id: id }, 415);
      let pages: Uint8Array[]; try { pages = await splitPdf(bytes); } catch (e) { return response({ error: "Could not split PDF into pages", provider_error: e instanceof Error ? e.message : String(e), request_id: id }, 422); }
      await log(id, "info", "PDF_SPLIT", "PDF split into one-page documents before provider parsing", { name: file.name, original_size: file.size, page_count: pages.length, page_sizes: pages.map(p => p.length) });
      for (let i = 0; i < pages.length; i++) { const pageNumber = i + 1; const pageFileName = `${file.name.replace(/\.pdf$/i, "")}-page-${pageNumber}.pdf`; await log(id, "info", "PAGE_REQUEST", "Sending one PDF page for structured extraction", { name: file.name, page: pageNumber, page_count: pages.length, page_size: pages[i].length, engine: "cloudflare-ai" }); let result = await requestPdfExtraction(openRouterKey, pageFileName, pages[i], pageNumber, pages.length, "cloudflare-ai"); let engine = "cloudflare-ai"; if (!result.ok && isSizeParserError(result.status, result.detail)) { await log(id, "warn", "PAGE_PARSER_SIZE_FALLBACK", "Cloudflare PDF parser rejected the page size; retrying this page with Mistral OCR", { name: file.name, page: pageNumber, page_size: pages[i].length, cloudflare_error: result.detail }); result = await requestPdfExtraction(openRouterKey, pageFileName, pages[i], pageNumber, pages.length, "mistral-ocr"); engine = "mistral-ocr"; } if (!result.ok) { await log(id, "error", "OPENROUTER_RESPONSE", "Structured extraction provider failed for PDF page", { status: result.status, provider_error: result.detail, name: file.name, page: pageNumber, engine }); return response({ error: "Structured extraction provider failed", status: result.status, provider_error: result.detail, request_id: id, page: pageNumber }, 502); } department = department || result.parsed.department; department_code = department_code || result.parsed.department_code; const pageRows = cleanRows(result.parsed).map((r: any) => ({ ...r, source_page: pageNumber })); all.push(...pageRows); await log(id, "info", "PAGE_COMPLETE", "PDF page converted to normalized rows", { name: file.name, page: pageNumber, rows: pageRows.length, engine, provider_model: result.provider_model }); }
    }
    const persisted = await rpc("persist_department_schedule_extraction", { target: { programme: CONTEXT.academic_program, term: CONTEXT.academic_term, batch: CONTEXT.batch, from: CONTEXT.period_start, to: CONTEXT.period_end }, department: department || "Unknown Department", department_code, source_file: files.map(f => f.name).join(", "), files_count: files.length, source_type: files.length === 1 && files[0].name.toLowerCase().endsWith(".csv") ? "spreadsheet" : files[0].type === "application/pdf" ? "pdf" : "image", extractor_version: "v2.4.3-page-chunked", classes: all });
    await log(id, "info", "STRUCTURED_INGEST_COMPLETE", "Structured rows persisted without reconciliation", { ...persisted }); return response({ ok: true, request_id: id, model: MODEL, context: CONTEXT, department: department || "Unknown Department", classes: all, persistence: persisted, reconciliation: false });
  } catch (e) { await log(id, "error", "INGEST_EXCEPTION", "Structured ingest failed", { error: e instanceof Error ? e.message : String(e) }); return response({ error: e instanceof Error ? e.message : String(e), request_id: id }, 500); }
});
