create table if not exists public.schedule_agent_logs (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  created_at timestamptz not null default now(),
  level text not null default 'info' check (level in ('debug','info','warn','error')),
  stage text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists idx_schedule_agent_logs_created_at on public.schedule_agent_logs(created_at desc);
create index if not exists idx_schedule_agent_logs_request_id on public.schedule_agent_logs(request_id, created_at);
alter table public.schedule_agent_logs enable row level security;
create or replace function public.append_schedule_agent_log(p_request_id uuid, p_level text, p_stage text, p_message text, p_metadata jsonb default '{}'::jsonb)
returns public.schedule_agent_logs language sql security definer set search_path = public as $$
  insert into public.schedule_agent_logs(request_id, level, stage, message, metadata)
  values (p_request_id, lower(coalesce(p_level,'info')), p_stage, p_message, coalesce(p_metadata,'{}'::jsonb)) returning *;
$$;
revoke all on function public.append_schedule_agent_log(uuid,text,text,text,jsonb) from public;
grant execute on function public.append_schedule_agent_log(uuid,text,text,text,jsonb) to anon, authenticated;
create or replace function public.get_schedule_agent_logs(p_limit integer default 200)
returns setof public.schedule_agent_logs language sql security definer set search_path = public as $$
  select * from public.schedule_agent_logs order by created_at desc limit greatest(1, least(coalesce(p_limit,200),1000));
$$;
revoke all on function public.get_schedule_agent_logs(integer) from public;
grant execute on function public.get_schedule_agent_logs(integer) to anon, authenticated;